export const dummyHospitals = [
  {
    id: 1,
    name: "서울중앙병원",
    address: "서울특별시 중구 세종대로 110",
    phone: "02-1234-0001",
    website: "https://seoulhospital1.example.com",
    description: "최신 장비를 갖춘 종합병원입니다.",
    latitude: 37.5665,
    longitude: 126.978,
    department: "내과",
    rating: 4.5,
    operatingHours: "09:00 - 18:00",
    openTime: { hour: 9, minute: 0, second: 0, nano: 0 },
    closeTime: { hour: 18, minute: 0, second: 0, nano: 0 },
    lunchStart: { hour: 12, minute: 0, second: 0, nano: 0 },
    lunchEnd: { hour: 13, minute: 0, second: 0, nano: 0 },
    isEmergency: true,
    isActive: true,
    parkingAvailable: true,
    wheelchairAccessible: true,
    specializedTreatments: "암 치료",
    distance: 1.2,
    isOpen: true,
    googlePlaceId: "ChIJ1-Hospital",
    userRatingsTotal: 120,
  },
  {
    id: 2,
    name: "강남서울의원",
    address: "서울특별시 강남구 테헤란로 212",
    phone: "02-1234-0002",
    website: "https://seoulhospital2.example.com",
    description: "친절한 진료로 유명한 의원입니다.",
    latitude: 37.5078,
    longitude: 127.0631,
    department: "소아과",
    rating: 4.2,
    operatingHours: "09:00 - 18:00",
    openTime: { hour: 9, minute: 0, second: 0, nano: 0 },
    closeTime: { hour: 18, minute: 0, second: 0, nano: 0 },
    lunchStart: { hour: 12, minute: 0, second: 0, nano: 0 },
    lunchEnd: { hour: 13, minute: 0, second: 0, nano: 0 },
    isEmergency: false,
    isActive: true,
    parkingAvailable: true,
    wheelchairAccessible: false,
    specializedTreatments: "피부관리",
    distance: 2.1,
    isOpen: true,
    googlePlaceId: "ChIJ2-Hospital",
    userRatingsTotal: 85,
  },
  {
    id: 3,
    name: "용산재활의학과",
    address: "서울특별시 용산구 한강대로 92",
    phone: "02-1234-0003",
    website: "https://seoulhospital3.example.com",
    description: "재활 전문 클리닉입니다.",
    latitude: 37.5349,
    longitude: 126.9904,
    department: "정형외과",
    rating: 4.0,
    operatingHours: "09:00 - 18:00",
    openTime: { hour: 9, minute: 0, second: 0, nano: 0 },
    closeTime: { hour: 18, minute: 0, second: 0, nano: 0 },
    lunchStart: { hour: 12, minute: 30, second: 0, nano: 0 },
    lunchEnd: { hour: 13, minute: 30, second: 0, nano: 0 },
    isEmergency: true,
    isActive: true,
    parkingAvailable: false,
    wheelchairAccessible: true,
    specializedTreatments: "재활치료",
    distance: 0.9,
    isOpen: true,
    googlePlaceId: "ChIJ3-Hospital",
    userRatingsTotal: 60,
  },
  {
    id: 26,
    name: "한빛성모병원",
    address: "서울특별시 마포구 양화로 45",
    phone: "02-5678-0026",
    website: "https://hanbit-hospital.example.com",
    description: "24시간 응급실 운영, 소화기 전문 병원입니다.",
    latitude: 37.5563,
    longitude: 126.9225,
    department: "소화기내과",
    rating: 4.7,
    operatingHours: "24시간 운영",
    openTime: { hour: 0, minute: 0, second: 0, nano: 0 },
    closeTime: { hour: 23, minute: 59, second: 59, nano: 0 },
    lunchStart: { hour: 0, minute: 0, second: 0, nano: 0 },
    lunchEnd: { hour: 0, minute: 0, second: 0, nano: 0 },
    isEmergency: true,
    isActive: true,
    parkingAvailable: true,
    wheelchairAccessible: true,
    specializedTreatments: "내시경 검사",
    distance: 2.4,
    isOpen: true,
    googlePlaceId: "ChIJ26-Hospital",
    userRatingsTotal: 188,
  },
  {
    id: 27,
    name: "서울365정형외과의원",
    address: "서울특별시 강동구 천호대로 1025",
    phone: "02-5678-0027",
    website: "https://seoul365ortho.example.com",
    description: "관절, 척추 통증 전문 클리닉입니다.",
    latitude: 37.5388,
    longitude: 127.1244,
    department: "정형외과",
    rating: 4.3,
    operatingHours: "09:00 - 20:00",
    openTime: { hour: 9, minute: 0, second: 0, nano: 0 },
    closeTime: { hour: 20, minute: 0, second: 0, nano: 0 },
    lunchStart: { hour: 13, minute: 0, second: 0, nano: 0 },
    lunchEnd: { hour: 14, minute: 0, second: 0, nano: 0 },
    isEmergency: false,
    isActive: true,
    parkingAvailable: false,
    wheelchairAccessible: true,
    specializedTreatments: "도수치료",
    distance: 3.1,
    isOpen: true,
    googlePlaceId: "ChIJ27-Hospital",
    userRatingsTotal: 102,
  },
  {
    id: 28,
    name: "이화여자대학교부속서울병원",
    address: "서울특별시 중구 충무로 49",
    phone: "02-5678-0028",
    website: "https://ewha-seoul.example.com",
    description: "여성 및 소아 전문 종합병원입니다.",
    latitude: 37.5641,
    longitude: 126.9946,
    department: "산부인과",
    rating: 4.8,
    operatingHours: "08:00 - 17:00",
    openTime: { hour: 8, minute: 0, second: 0, nano: 0 },
    closeTime: { hour: 17, minute: 0, second: 0, nano: 0 },
    lunchStart: { hour: 12, minute: 30, second: 0, nano: 0 },
    lunchEnd: { hour: 13, minute: 30, second: 0, nano: 0 },
    isEmergency: true,
    isActive: true,
    parkingAvailable: true,
    wheelchairAccessible: true,
    specializedTreatments: "여성질환",
    distance: 1.7,
    isOpen: true,
    googlePlaceId: "ChIJ28-Hospital",
    userRatingsTotal: 230,
  },
  {
    id: 29,
    name: "삼성서울가정의학과",
    address: "서울특별시 송파구 올림픽로 35",
    phone: "02-5678-0029",
    website: "https://samsungclinic.example.com",
    description: "건강검진과 만성질환 관리 전문 의원입니다.",
    latitude: 37.5142,
    longitude: 127.1056,
    department: "가정의학과",
    rating: 4.4,
    operatingHours: "09:00 - 17:30",
    openTime: { hour: 9, minute: 0, second: 0, nano: 0 },
    closeTime: { hour: 17, minute: 30, second: 0, nano: 0 },
    lunchStart: { hour: 12, minute: 30, second: 0, nano: 0 },
    lunchEnd: { hour: 13, minute: 30, second: 0, nano: 0 },
    isEmergency: false,
    isActive: true,
    parkingAvailable: true,
    wheelchairAccessible: true,
    specializedTreatments: "건강검진",
    distance: 1.6,
    isOpen: true,
    googlePlaceId: "ChIJ29-Hospital",
    userRatingsTotal: 76,
  },
  {
    id: 30,
    name: "연세서울이비인후과",
    address: "서울특별시 은평구 불광로 145",
    phone: "02-5678-0030",
    website: "https://yonsei-ent.example.com",
    description: "귀, 코, 목 전문 클리닉입니다.",
    latitude: 37.6183,
    longitude: 126.9229,
    department: "이비인후과",
    rating: 4.1,
    operatingHours: "10:00 - 19:00",
    openTime: { hour: 10, minute: 0, second: 0, nano: 0 },
    closeTime: { hour: 19, minute: 0, second: 0, nano: 0 },
    lunchStart: { hour: 13, minute: 0, second: 0, nano: 0 },
    lunchEnd: { hour: 14, minute: 0, second: 0, nano: 0 },
    isEmergency: false,
    isActive: true,
    parkingAvailable: false,
    wheelchairAccessible: false,
    specializedTreatments: "알레르기 치료",
    distance: 3.3,
    isOpen: true,
    googlePlaceId: "ChIJ30-Hospital",
    userRatingsTotal: 64,
  },
  {
    id: 31,
    name: "서울대치과병원",
    address: "서울특별시 종로구 대학로 101",
    phone: "02-5678-0031",
    website: "https://seouldental.example.com",
    description: "임플란트, 교정 전문 대학병원 치과입니다.",
    latitude: 37.5796,
    longitude: 126.9982,
    department: "치과",
    rating: 4.9,
    operatingHours: "08:30 - 17:30",
    openTime: { hour: 8, minute: 30, second: 0, nano: 0 },
    closeTime: { hour: 17, minute: 30, second: 0, nano: 0 },
    lunchStart: { hour: 12, minute: 30, second: 0, nano: 0 },
    lunchEnd: { hour: 13, minute: 30, second: 0, nano: 0 },
    isEmergency: true,
    isActive: true,
    parkingAvailable: true,
    wheelchairAccessible: true,
    specializedTreatments: "임플란트",
    distance: 0.7,
    isOpen: true,
    googlePlaceId: "ChIJ31-Hospital",
    userRatingsTotal: 213,
  },
  {
    id: 32,
    name: "해돋는다감요양병원",
    address: "서울특별시 노원구 공릉로 182",
    phone: "02-5678-0032",
    website: "https://hedawncare.example.com",
    description: "고령자와 만성질환자 위한 장기요양 병원입니다.",
    latitude: 37.6231,
    longitude: 127.0837,
    department: "요양병원",
    rating: 4.0,
    operatingHours: "24시간 운영",
    openTime: { hour: 0, minute: 0, second: 0, nano: 0 },
    closeTime: { hour: 23, minute: 59, second: 59, nano: 0 },
    lunchStart: { hour: 12, minute: 0, second: 0, nano: 0 },
    lunchEnd: { hour: 13, minute: 0, second: 0, nano: 0 },
    isEmergency: false,
    isActive: true,
    parkingAvailable: true,
    wheelchairAccessible: true,
    specializedTreatments: "치매 케어",
    distance: 4.5,
    isOpen: true,
    googlePlaceId: "ChIJ32-Hospital",
    userRatingsTotal: 54,
  },
  {
    id: 33,
    name: "강북삼성한방병원",
    address: "서울특별시 강북구 도봉로 75",
    phone: "02-5678-0033",
    website: "https://kbsamsungh.example.com",
    description: "침, 뜸, 한약 전문 치료 한방병원입니다.",
    latitude: 37.6391,
    longitude: 127.0254,
    department: "한방과",
    rating: 4.6,
    operatingHours: "09:00 - 18:00",
    openTime: { hour: 9, minute: 0, second: 0, nano: 0 },
    closeTime: { hour: 18, minute: 0, second: 0, nano: 0 },
    lunchStart: { hour: 12, minute: 0, second: 0, nano: 0 },
    lunchEnd: { hour: 13, minute: 0, second: 0, nano: 0 },
    isEmergency: false,
    isActive: true,
    parkingAvailable: true,
    wheelchairAccessible: false,
    specializedTreatments: "한방 침 치료",
    distance: 3.9,
    isOpen: true,
    googlePlaceId: "ChIJ33-Hospital",
    userRatingsTotal: 97,
  },
];
