export const dummyHospitals = [
  {
    id: 1,
    name: "서울센트럴정신건강의학과의원",
    address: "서울특별시 중구 세종대로 11",
    phone: "02-779-7660",
    website: "https://en.seoulcentralmhc.com",
    description: "영어진료 가능, 우울증·불안장애 전문 클리닉입니다.",
    latitude: 37.5665,
    longitude: 126.9780,
    department: "정신건강의학과",
    rating: 4.6,
    operatingHours: "09:00 - 18:00",
    openTime: { hour: 9, minute: 0, second: 0, nano: 0 },
    closeTime: { hour: 18, minute: 0, second: 0, nano: 0 },
    lunchStart: { hour: 12, minute: 30, second: 0, nano: 0 },
    lunchEnd: { hour: 13, minute: 30, second: 0, nano: 0 },
    isEmergency: false,
    isActive: true,
    parkingAvailable: false,
    wheelchairAccessible: true,
    specializedTreatments: "우울증, 불안장애",
    distance: 1.2,
    isOpen: true,
    googlePlaceId: "ChIJ-seoulcentral",
    userRatingsTotal: 120,
  },
  {
    id: 2,
    name: "Seoul Psychiatry Gangnam (서울 정신건강의학과)",
    address: "서울특별시 강남구 선릉로 517 Vision빌딩 6층",
    phone: "02-3453-8856",
    website: "https://www.seoulpsychiatryclinic.com",
    description: "영어 진료, rTMS 포함 최신 치료 제공",
    latitude: 37.5079,
    longitude: 127.0632,
    department: "정신건강의학과",
    rating: 4.7,
    operatingHours: "09:00 - 18:00",
    openTime: { hour: 9, minute: 0, second: 0, nano: 0 },
    closeTime: { hour: 18, minute: 0, second: 0, nano: 0 },
    lunchStart: { hour: 12, minute: 30, second: 0, nano: 0 },
    lunchEnd: { hour: 13, minute: 30, second: 0, nano: 0 },
    isEmergency: false,
    isActive: true,
    parkingAvailable: false,
    wheelchairAccessible: true,
    specializedTreatments: "우울증, 불안, ADHD, rTMS",
    distance: 2.1,
    isOpen: true,
    googlePlaceId: "ChIJ-seoulpsychiatry",
    userRatingsTotal: 85,
  },
  {
    id: 3,
    name: "광화문숲정신건강의학과의원",
    address: "서울특별시 종로구 청진동",
    phone: "정보 없음",
    website: "",
    description: "야간 진료 가능, 종로 지역 정신건강 클리닉",
    latitude: 37.5710,
    longitude: 126.9769,
    department: "정신건강의학과",
    rating: 4.5,
    operatingHours: "10:00 - 20:00",
    openTime: { hour: 10, minute: 0, second: 0, nano: 0 },
    closeTime: { hour: 20, minute: 0, second: 0, nano: 0 },
    lunchStart: { hour: 14, minute: 0, second: 0, nano: 0 },
    lunchEnd: { hour: 15, minute: 0, second: 0, nano: 0 },
    isEmergency: false,
    isActive: true,
    parkingAvailable: true,
    wheelchairAccessible: true,
    specializedTreatments: "우울증, 불안, 스트레스",
    distance: 0.9,
    isOpen: true,
    googlePlaceId: "ChIJ-gwanghwamun",
    userRatingsTotal: 60,
  },
  {
    id: 4,
    name: "민트정신건강의학과의원",
    address: "서울특별시 중구 서소문동",
    phone: "정보 없음",
    website: "",
    description: "야간 진료, 서소문 지역 정신과 의원",
    latitude: 37.5630,
    longitude: 126.9750,
    department: "정신건강의학과",
    rating: 4.4,
    operatingHours: "09:00 - 21:00",
    openTime: { hour: 9, minute: 0, second: 0, nano: 0 },
    closeTime: { hour: 21, minute: 0, second: 0, nano: 0 },
    lunchStart: { hour: 13, minute: 0, second: 0, nano: 0 },
    lunchEnd: { hour: 14, minute: 0, second: 0, nano: 0 },
    isEmergency: false,
    isActive: true,
    parkingAvailable: false,
    wheelchairAccessible: true,
    specializedTreatments: "야간진료, 스트레스, 불안",
    distance: 1.7,
    isOpen: true,
    googlePlaceId: "ChIJ-mintclinic",
    userRatingsTotal: 102,
  },
  {
    id: 5,
    name: "서울대학교병원 정신건강의학과",
    address: "서울특별시 종로구 연건동",
    phone: "02-2072-1234",
    website: "https://health4u.snu.ac.kr",
    description: "24시간 진료, 상급종합병원 정신건강 센터",
    latitude: 37.5890,
    longitude: 126.9985,
    department: "정신건강의학과",
    rating: 4.8,
    operatingHours: "24시간",
    openTime: { hour: 0, minute: 0, second: 0, nano: 0 },
    closeTime: { hour: 23, minute: 59, second: 59, nano: 0 },
    lunchStart: { hour: 0, minute: 0, second: 0, nano: 0 },
    lunchEnd: { hour: 0, minute: 0, second: 0, nano: 0 },
    isEmergency: true,
    isActive: true,
    parkingAvailable: true,
    wheelchairAccessible: true,
    specializedTreatments: "종합 정신건강 진료, 연구 및 스트레스 관리",
    distance: 0.7,
    isOpen: true,
    googlePlaceId: "ChIJ-snumhc",
    userRatingsTotal: 213,
  },
  {
    id: 6,
    name: "서울특별시백암정신병원",
    address: "서울특별시 동작구 백암로",
    phone: "02-870-9111",
    website: "https://m.baekammh.or.kr",
    description: "공공정신병원, 입원치료 및 외래 진료",
    latitude: 37.5000,
    longitude: 126.9440,
    department: "정신병원",
    rating: 4.3,
    operatingHours: "24시간",
    openTime: { hour: 0, minute: 0, second: 0, nano: 0 },
    closeTime: { hour: 23, minute: 59, second: 59, nano: 0 },
    lunchStart: { hour: 12, minute: 0, second: 0, nano: 0 },
    lunchEnd: { hour: 13, minute: 0, second: 0, nano: 0 },
    isEmergency: true,
    isActive: true,
    parkingAvailable: true,
    wheelchairAccessible: true,
    specializedTreatments: "입원치료, 중증정신질환 관리",
    distance: 4.5,
    isOpen: true,
    googlePlaceId: "ChIJ-baekam",
    userRatingsTotal: 54,
  },
];